TOOLPATH = ./z_tools/

include $(TOOLPATH)command.txt


all:
#	$(TOOLPATH)make -C gcc
	$(TOOLPATH)make -C golib00
#	$(EFG) golib00 out:w32clibc/libmingw.lib libmingw/libmingw_o/_chkstk.o libmingw/libmingw_o/dt.o libmingw/libmingw_o/dh.o libmingw/libmingw_o/ds00027.o libmingw/libmingw_o/ds00053.o libmingw/libmingw_o/ds00130.o libmingw/libmingw_o/ds00207.o libmingw/libmingw_o/ds00277.o libmingw/libmingw_o/ds00342.o libmingw/libmingw_o/ds00535.o libmingw/libmingw_o/ds00724.o libmingw/libmingw_o/ds00323.o libmingw/libmingw_o/ds00415.o libmingw/libmingw_o/ds00421.o libmingw/libmingw_o/ds00424.o libmingw/libmingw_o/ds00175.o libmingw/libmingw_o/ds00611.o libmingw/libmingw_o/ds00088.o libmingw/libmingw_o/ds00070.o libmingw/libmingw_o/ds00272.o libmingw/libmingw_o/ds00727.o
	$(TOOLPATH)make -C w32clibc
	$(TOOLPATH)make -C golibc

	$(TOOLPATH)make -C akusA
	$(TOOLPATH)make -C bin2obj
	$(TOOLPATH)make -C doscmd
	$(TOOLPATH)make -C makefont
	$(TOOLPATH)make -C Nasuka
	$(TOOLPATH)make -C hrblib0a
	$(TOOLPATH)make -C obj2bim
	$(TOOLPATH)make -C bim2hrb
	$(TOOLPATH)make -C imgtol
	$(TOOLPATH)make -C osalink1
	$(TOOLPATH)make -C naskcnv0
	$(TOOLPATH)make -C bim2g01
	$(TOOLPATH)make -C bin2ucc
	$(TOOLPATH)make -C gas2nask
	$(TOOLPATH)make -C sjisconv
	$(TOOLPATH)make -C rjcg01
	$(TOOLPATH)make -C cpy
	$(TOOLPATH)make -C cpyc
	$(TOOLPATH)make -C mtek2org
	$(TOOLPATH)make -C tekmin0
	$(TOOLPATH)make -C tekmin1




clean :
#	$(TOOLPATH)make -C gcc       clean
#	$(TOOLPATH)make -C go_lib    clean
#	$(TOOLPATH)make -C libiberty clean
#	$(TOOLPATH)make -C intl      clean
#	$(TOOLPATH)make -C drv_w32   clean
#	$(TOOLPATH)make -C drv_stdc  clean
#	$(TOOLPATH)make -C drv_osa   clean
	$(TOOLPATH)make -C golib00 clean
	$(TOOLPATH)make -C golibc    clean
	$(TOOLPATH)make -C w32clibc  clean
	$(TOOLPATH)make -C akusA   clean
	$(TOOLPATH)make -C bin2obj   clean
	$(TOOLPATH)make -C doscmd   clean
	$(TOOLPATH)make -C makefont   clean
	$(TOOLPATH)make -C Nasuka clean
	$(TOOLPATH)make -C golib00 clean
	$(TOOLPATH)make -C hrblib0a   clean
	$(TOOLPATH)make -C obj2bim  clean
	$(TOOLPATH)make -C bim2hrb  clean
	$(TOOLPATH)make -C imgtol  clean
	$(TOOLPATH)make -C osalink1 clean
	$(TOOLPATH)make -C naskcnv0 clean
	$(TOOLPATH)make -C bim2g01 clean
	$(TOOLPATH)make -C bin2ucc clean
	$(TOOLPATH)make -C gas2nask clean
	$(TOOLPATH)make -C sjisconv clean
	$(TOOLPATH)make -C rjcg01 clean
	$(TOOLPATH)make -C cpy clean
	$(TOOLPATH)make -C cpyc clean
	$(TOOLPATH)make -C mtek2org clean
	$(TOOLPATH)make -C tekmin0 clean
	$(TOOLPATH)make -C tekmin1 clean
