include ./z_tools/command.txt



# デフォルト動作


all :
	$(MAKE) -C calc
	$(MAKE) -C calc1
	$(MAKE) -C calendar
	$(MAKE) -C calendrc
	$(MAKE) -C cclsc0
	$(MAKE) -C ccolorc0
	$(MAKE) -C chars
	$(MAKE) -C cntup0
	$(MAKE) -C cpy
	$(MAKE) -C cpyc
	$(MAKE) -C dmparg
	$(MAKE) -C echoc
	$(MAKE) -C hello
	$(MAKE) -C helloc
	$(MAKE) -C helloc1
	$(MAKE) -C hexdump
	$(MAKE) -C pi
	$(MAKE) -C tcns00a
	$(MAKE) -C tcns00b
	$(MAKE) -C tcns01a
	$(MAKE) -C tcns02a
	$(MAKE) -C tcns02b
	$(MAKE) -C tcns03a
	$(MAKE) -C tcns04a
	$(MAKE) -C testkey0
	$(MAKE) -C testkey1


clean :
	$(MAKE) -C calc	clean
	$(MAKE) -C calc1	clean
	$(MAKE) -C calendar	clean
	$(MAKE) -C calendrc	clean
	$(MAKE) -C cclsc0	clean
	$(MAKE) -C ccolorc0	clean
	$(MAKE) -C chars	clean
	$(MAKE) -C cntup0	clean
	$(MAKE) -C cpy	clean
	$(MAKE) -C cpyc	clean
	$(MAKE) -C dmparg	clean
	$(MAKE) -C echoc	clean
	$(MAKE) -C hello	clean
	$(MAKE) -C helloc	clean
	$(MAKE) -C helloc1	clean
	$(MAKE) -C hexdump	clean
	$(MAKE) -C pi	clean
	$(MAKE) -C tcns00a	clean
	$(MAKE) -C tcns00b	clean
	$(MAKE) -C tcns01a	clean
	$(MAKE) -C tcns02a	clean
	$(MAKE) -C tcns02b	clean
	$(MAKE) -C tcns03a	clean
	$(MAKE) -C tcns04a	clean
	$(MAKE) -C testkey0	clean
	$(MAKE) -C testkey1	clean




install :
	$(MAKE) -C calc	install
	$(MAKE) -C calc1	install
	$(MAKE) -C calendar	install
	$(MAKE) -C calendrc	install
	$(MAKE) -C cclsc0	install
	$(MAKE) -C ccolorc0	install
	$(MAKE) -C chars	install
	$(MAKE) -C cntup0	install
	$(MAKE) -C cpy	install
	$(MAKE) -C cpyc	install
	$(MAKE) -C dmparg	install
	$(MAKE) -C echoc	install
	$(MAKE) -C hello	install
	$(MAKE) -C helloc	install
	$(MAKE) -C helloc1	install
	$(MAKE) -C hexdump	install
	$(MAKE) -C pi	install
	$(MAKE) -C tcns00a	install
	$(MAKE) -C tcns00b	install
	$(MAKE) -C tcns01a	install
	$(MAKE) -C tcns02a	install
	$(MAKE) -C tcns02b	install
	$(MAKE) -C tcns03a	install
	$(MAKE) -C tcns04a	install
	$(MAKE) -C testkey0	install
	$(MAKE) -C testkey1	install






