include ../z_tools/command.txt

TARGET = Nasuka
MODE   = g01
OBJS   = $(TARGET).obj Nasuka_sub.obj ll.obj ll_lib.obj mmmalloc.obj

INCPATH    = ../z_tools/guigui01/
include ../z_tools/com_mak.txt
