include ../z_tools/command.txt

TARGET = g01libc1
MODE   = lib
OBJS   = g01_esi0.obj bss1a1.obj bss1a2.obj bss1a4.obj bss1a8.obj bss1a16.obj

INCPATH    = ../z_tools/guigui01/
include ../z_tools/com_mak.txt
